server:
  port: 30402

# spring 配置
spring:
  application:
    name: alinesno-infra-ops-telemetry-boot
  datasource:
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    url: jdbc:clickhouse://localhost:8123/default
    username: default
  data:
    redis:
     host: localhost
     port: 6379
     timeout: 10s
  kafka:
    bootstrap-servers:
      - localhost:9092
  devtools:
    restart:
      enabled: true