server:
  port: 30402

# spring 配置
spring:
  application:
    name: alinesno-infra-ops-telemetry-boot
  datasource:
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    url: jdbc:clickhouse://localhost:8123/default
    username: default
  data:
    redis:
     host: localhost
     port: 6379
     password: aip@local
     timeout: 10s
  kafka:
    bootstrap-servers:
      - localhost:9092
  devtools:
    restart:
      enabled: true

# sa-token配置
sa-token:
  token-name: satoken
  host-path: http://alinesno-infra-base-identity-auth-application.beta.base.infra.linesno.com
  sso:
    auth-url: ${sa-token.host-path}/login
    is-http: true
    check-ticket-url: ${sa-token.host-path}/sso/checkTicket
    slo-url: ${sa-token.host-path}/sso/signout
    get-data-url: ${sa-token.host-path}/sso/getData
  sign:
    secret-key:
