-- 应用预警表设计
-- DROP TABLE public.alerts;
CREATE TABLE alerts (
	id bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
	project_id int NOT NULL COMMENT '项目ID',
	dedup_hash bigint NOT NULL COMMENT '去重哈希',
	`name` varchar(1000) NOT NULL COMMENT '名称',
	state enum('ALERT_STATE_ENUM') NOT NULL COMMENT '状态',
	monitor_id bigint NULL COMMENT '监控器ID',
	trackable_model enum('TRACKABLE_MODEL_ENUM') NULL COMMENT '可追踪模型',
	trackable_id bigint NULL COMMENT '可追踪ID',
	attrs json NULL COMMENT '属性',
	attrs_hash bigint NOT NULL COMMENT '属性哈希',
	tsv tsvector NULL COMMENT '文本搜索向量',
	`type` enum('ALERT_TYPE_ENUM') NOT NULL COMMENT '类型',
	params json NULL COMMENT '参数',
	created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (id),
	INDEX alerts_monitor_id_idx (monitor_id),
	UNIQUE INDEX alerts_project_id_dedup_hash_unq (project_id, dedup_hash),
	FULLTEXT INDEX alerts_project_id_tsv_idx (project_id, tsv)
);

-- 预警事件表
CREATE TABLE alert_events (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) COMMENT 'ID',
	user_id bigint NULL COMMENT '用户ID',
	project_id int NOT NULL COMMENT '项目ID',
	alert_id bigint NOT NULL COMMENT '警报ID',
	`name` enum('ALERT_EVENT_NAME_ENUM') NOT NULL COMMENT '名称',
	params jsonb NULL COMMENT '参数',
	created_at timestamptz NOT NULL DEFAULT now() COMMENT '创建时间',
	PRIMARY KEY (id)
);
